# Generated by Django 4.1.1 on 2023-03-03 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_membership_user_bday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_event',
            name='reg_ecert_no',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Event eCertificate Number'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_datecreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user_dateupdated',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='register_event',
            name='reg_payment_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 10, 7, 47, 709610, tzinfo=datetime.timezone.utc)),
        ),
    ]
